version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username "sanjaydevari" --password "sanjay@0023"
  build:
    commands:
      - echo Building Docker image...
      - docker build -t "sanjaydevari/candycrush-clone:v1" .
artifacts:
    files:
         - '**/*'



